/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package de.codecentric.iot.rapiro.movement.model {

    [RemoteClass(alias="de.codecentric.iot.rapiro.movement.model.Position")]
    public class Position extends PositionBase {
    }
}