/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package de.codecentric.iot.rapiro.telemetry.model {

    [RemoteClass(alias="de.codecentric.iot.rapiro.telemetry.model.TelemetryData")]
    public class TelemetryData extends TelemetryDataBase {
    }
}